---
resources:
- name: interstellar_space
  type: git
  source:
    uri: https://github.com/sshariff01/interstellar_space
    branch: master

jobs:
- name: tests
  plan:
  - get: interstellar_space
    trigger: true
  - task: all
    config:
      platform: linux
      inputs:
      - name: interstellar_space
      image_resource:
        type: docker-image
        source:
          repository: bitnami/rails
      run:
        path: ci/run_tests.sh
        dir: interstellar_space
        user: root
