---
resources:
- name: interstellar_space
  type: git
  source:
    uri: https://github.com/sshariff01/interstellar_space
    branch: master

jobs:
- name: unit-test
  plan:
  - get: interstellar_space
    trigger: true
  - task: run-unit-tests
    config:
      platform: linux
      inputs:
      - name: interstellar_space
      image_resource:
        type: docker-image
        source:
          repository: sshariff/rails-postgres
      run:
        path: ci/run_unit_tests.sh
        dir: interstellar_space

- name: acceptance-test
  plan:
  - get: interstellar_space
    passed: [unit-test]
    trigger: true
  - task: run-acceptance-tests
    config:
      platform: linux
      inputs:
      - name: interstellar_space
      image_resource:
        type: docker-image
        source:
          repository: sshariff/rails-postgres
      run:
        path: ci/run_acceptance_tests.sh
        dir: interstellar_space
